---
title: "Navigating Hostility"
subtitle: "The Effect of Nonprofit Transparency and Accountability on Donor Preferences in the Face of Shrinking Civic Space"
author: "Suparna Chaudhry, Marc Dotson, and Andrew Heiss"
format:
  html:
    code-tools: false
    toc: false
---

## Abstract

Governments across the world have increasingly used laws to restrict the work of nonprofits, which has led to a reduction in public or official foreign aid directed towards these groups. Many international nonprofits, in response, have turned to individual donors to offset the loss of traditional funding. What are individual donors' preferences regarding donating to legally besieged nonprofits abroad? We conducted a conjoint experiment on a nationally representative sample of likely donors in the US and found that learning about host government criticism and legal restrictions on nonprofits decreases individuals' preferences to donate to them. However, organizational features such as financial transparency and accountability can protect against this dampening effect. Our results have important implications both for understanding private international philanthropy and how nonprofits can better frame their fundraising appeals at a time when they are facing restrictive civic spaces and hostile governments abroad.

## Code

All the raw code and data for this paper is available in a [GitHub repository](https://github.com/andrewheiss/silent-skywalk).
