project:
  output-dir: output
  title: "Manuscript"

  render: 
    - "manuscript.qmd"
    - "appendix.qmd"

language: 
  title-block-published: Latest version
  related-formats-title: Other formats
  other-links-title: Other links

# This is necessary to keep intermediate files/folders hanging around when
# rendering to the same output format (like two different PDFs)
# https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-1979245883
keep-md: true

format:
  # Nice HTML output
  html:
    toc: true
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>
    shift-heading-level-by: 1
    theme:
      - zephyr
      - html/custom.scss

    citeproc: false
    filters:
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/citeproc.lua
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/wordcount.lua

    format-links:
      - html
      - format: hikmah-pdf
        text: PDF
        icon: file-pdf
      - format: hikmah-manuscript-pdf+ms
        text: Manuscripty PDF
        icon: file-pdf

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300

  # Nice PDF output
  hikmah-pdf:
    cite-method: citeproc
    appendix-single-spacing: false

    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "IBM Plex Sans"
    mathfont: "Libertinus Math"
    # linestretch: 1.05

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small }

        \SetTblrStyle{foot}{font=\footnotesize}

    knitr:
      opts_chunk:
        dev: "cairo_pdf"

  # Manuscript-y PDF output
  hikmah-manuscript-pdf+ms:
    cite-method: citeproc
    left-aligned: true
    endnotes: true
    appendix-single-spacing: true

    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    mathfont: "Libertinus Math"

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \everydisplay\expandafter{\the\everydisplay\small }

        \SetTblrStyle{foot}{font=\footnotesize}

        \AtBeginEnvironment{longtblr}{\setlength{\RaggedRightParindent}{0pt}\singlespacing}
        \AtBeginEnvironment{Shaded}{\singlespacing}

        \NewTblrTheme{long}{
          \SetTblrStyle{caption}{hang=0pt}
          \SetTblrStyle{capcont}{hang=0pt}
          \SetTblrStyle{caption-tag}{font=\small}
          \SetTblrStyle{caption-text}{font=\small}
          \SetTblrStyle{conthead-text}{font=\small}
          \SetTblrStyle{contfoot}{font=\small}
        }

    knitr:
      opts_chunk:
        dev: "cairo_pdf"

  # Manuscript-y Word output
  #
  # This breaks with the "Politics, ideology, and religion" table in the 
  # appendix with this error:
  # Error in strrep(" ", col_widths[j] - nc): invalid 'times' value
  #
  # Maybe because group titles are too long?
  # 
  # hikmah-manuscript-docx: default
