---
title: Responses to reviewer concerns
format: hikmah-response-typst
bibliography: ../../references.bib
csl: ../../csl/chicago-author-date.csl
citeproc: true
link-citations: true
---

Thank you for giving us the opportunity to revise and resubmit our research article "Why Donors Donate: Disentangling Organizational and Structural Heuristics for International Philanthropy" (Manuscript ID `NVSQ-AR-23-0438`). We found the Reviewers' comments to be very insightful and helpful, as they identified several parts of the manuscript that were unclear and incomplete. In this memo, we describe how we have revised the paper in response to these comments. The Reviewers' comments are cited or summarized in [red italicized text]{.memo-reviewer-inline}, and our responses are in black Roman text. We include excerpts from our revised manuscript in [blue]{.memo-excerpt-inline}.

# Reviewer 1

::: {.memo-reviewer}
1. The authors may need to explain more about why choosing transparency and accountability as two organizational factors, given that there are many different organizational factors that donors may use for their donations.
:::

We thank Reviewer 1 for blah blah blah

::: {.memo-excerpt}
**[pp. 4–5]**: PASTE FROM RENDERED .QMD FILE
:::

---

::: {.memo-reviewer}
2. In Table 1, Relationship with host government has three levels: (a) Friendly relationship with government; (b) Criticized by government; (c) Under government crackdown. This organizational level measurement may not exactly capture the macro level shrinking civic space in many countries. Also, the authors may clearly state that the INGOs operate in countries where INGOs are controlled and constrained in the experiment.
:::

We thank Reviewer 1 for blah blah blah

::: {.memo-excerpt}
**[pp. x-xx]**: PASTE FROM RENDERED .QMD FILE
:::


# Reviewer 2

::: {.memo-reviewer}
X. Reviewer request/comment
:::

We thank Reviewer 2 for blah blah blah

::: {.memo-excerpt}
**[pp. x-xx]**: PASTE FROM RENDERED .QMD FILE
:::

---

::: {.memo-reviewer}
X. Reviewer request/comment
:::

We thank Reviewer 2 for blah blah blah

::: {.memo-excerpt}
**[pp. x-xx]**: PASTE FROM RENDERED .QMD FILE
:::

# Reviewer 3

::: {.memo-reviewer}
1. Why did you ask each respondent to review 12 scenarios?

   On page 16 line 33, you suggest that three NGOs were mentioned in each scenario the respondents considered (and then did this twelve tines). Is this a typo as it sounds very complex?
:::

Blah blah how we responded

::: {.memo-excerpt}
**[pp. x-xx]**: What we did
:::

---

::: {.memo-reviewer}
1. You should include some clearer discussion of how donation intention was operationalised in this discussion.
:::

Blah blah how we responded

::: {.memo-excerpt}
**[pp. x-xx]**: What we did
:::

---

::: {.memo-reviewer}
X. Reviewer request/comment
:::

We thank Reviewer 3 for blah blah blah

::: {.memo-excerpt}
**[pp. x-xx]**: PASTE FROM RENDERED .QMD FILE
:::

---

::: {.memo-reviewer}
X. Reviewer request/comment
:::

We thank Reviewer 3 for blah blah blah

::: {.memo-excerpt}
**[pp. x-xx]**: PASTE FROM RENDERED .QMD FILE
:::

---

# References
